apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: unleash-me-{{ environment }}
  namespace: {{ namespace }}
  labels:
    team: {{ team }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-For $http_x_forwarded_for";
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  liveness:
    path: "/health"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/health"
    initialDelay: 20
    timeout: 60
  envFrom:
    - secret: unleash-me
    - secret: "{{ azure_secret }}"
  env:
  {{#each env_variables}}
  - name: {{@key}}
    value: {{this}}
  {{/each}}
  azure:
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - "/public/*"
    application:
      allowAllUsers: true
      enabled: true
      replyURLs:
        - "http://localhost:8080/auth/callback"
        - "http://localhost:8081/auth/callback"
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    outbound:
      external:
        - host: "teampensjon-unleash-api.nav.cloud.nais.io"
  webproxy: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 64Mi

