name: "Build"

on:
  push:
    branches:
      - main

env:
  docker_image: ghcr.io/${{ github.repository }}
jobs:
  build:
    name: Build and publish docker container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.docker_image }}:${{ github.sha }}
            ${{ env.docker_image }}:latest
  deploy:
    name: Deploy unleash-me
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - vars: .nais/pensjon-saksbehandling-dev.yaml
            cluster: dev-gcp
            team: pensjon-saksbehandling

    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        name: "Deploy to cluster ${{ matrix.cluster }} for team ${{ matrix.team }}"
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml
          VAR: image_tag=${{ github.sha }}
          VARS: ${{ matrix.vars }}
          TEAM: ${{ matrix.team }}
