name: "Build"
on:
  push:
    branches:
      - "main"

env:
  docker_image: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  build:
    name: "Build and publish docker container"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v1"
        with:
          node-version: 18
      - name: "Login to GitHub Docker Registry"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.docker_image }}
